# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('n_comments', models.IntegerField()),
                ('n_pingbacks', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('authors', models.ManyToManyField(to='accounts.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField()),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NCSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_id', models.IntegerField()),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(7000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('s_block', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(max_length=15, unique=True)),
                ('s_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='s_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='order',
            name='s_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Register'),
        ),
        migrations.AddField(
            model_name='menu',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.NCSide'),
        ),
    ]
