# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='upload',
            field=models.FileField(default=datetime.datetime(2016, 2, 11, 14, 9, 37, 606745, tzinfo=utc), upload_to=b'media/'),
            preserve_default=False,
        ),
    ]
